version: "3.8"

services:
  db_server:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test_network

  api_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: bash -c "uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000"
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - test_network

volumes:
    postgres_data:

networks:
  test_network:
    driver: bridge
